FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libjpeg-dev \
    zlib1g-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["bash", "-c", "python db_scripts/minIO/scripts/generate_companies.py && python db_scripts/minIO/scripts/generate_documents.py && python backend/ocr_service/upload_to_minio.py"]
